// <auto-generated />
namespace SIGEVALP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DetallesEstadoAuthorizeRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DetallesEstadoAuthorizeRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "202206180247290_DetallesEstado & AuthorizeRoles "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
